num_tasks: 10
batch_size: 32
epochs_per_task: 100
out_dim: 384
lr: 0.1
momentum: 0.9
weight_decay: 5e-4
margin: 0.1
beta: 4.5
memory_size: 2000
replay_batch: 32
replay_lambda: 1
replay_on: true
seed: 1234
anchors_path: anchors/cifar100_anchors.pkl
checkpoints_dir: checkpoints
pretrained_backbone: True
milestones: [50, 75]