num_tasks: 10
batch_size: 32
epochs_per_task: 80
out_dim: 384
lr: 0.05
momentum: 0.9
weight_decay: 5e-4
margin: 0.1
beta: 4
memory_size: 2000
replay_batch: 32
replay_lambda: 1.0
replay_on: true
seed: 1234
anchors_path: anchors/cifar100_anchors.pkl
checkpoints_dir: checkpoints
pretrained_backbone: True
milestones: [30, 45]